apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: portal:0.2.0
        ports:
          - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: NODE_ENV
          value: "production"
        - name: VERSION
          value: 0.2.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: portal
spec:
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
